# file Makefile
# brief TOOD add your brief here
# author Jianlong Chen <jianlong99@gmail.com>
# date 2015-11-18
# $Id$

PROG = prexit\
	   return1\
	   return2\
	   sigfpe

all: $(PROG)

prexit: prexit.c
return1: return1.c
return2: return2.c
sigfpe: sigfpe.c

clean:
	$(Q) -rm $(PROG)
